### ISSUE TITLE
allow the user to choose between multiple forges

### ISSUE THREAD

**Issue by aaa006bd** [geprog/codecaptain#10]
- [x] #12
- [x] #14
- [x] #11
- [x] load forges from db
- [x] add additional forges (github and gitlab statically for the beginning)
- [x] allow user to add new forge via UI
- [x] Create UI for displaying multiple git providers
- [x] allow user to login with multiple forges (exp first create an account via github and then connect it to gitlab)

**Comment by aaa006bd** [comment]
@anbraten Please add or change the tasks if I am missing anyting.

**Comment by anbraten** [comment]
@aaa006bd Added some notes / steps
