### ISSUE TITLE
Seperate Issue Indexing

### ISSUE THREAD

**Issue by aaa006bd** [geprog/CodeCaptain#25]
@anbraten During my testing with bigger repositories I have encountered an error related to max token( Probably because we are trying to tokenize a l whole lot of texts from issues) which leads to faulty import. We should try to separate this. Maybe we can have a button that would only reindex the issues related to the repo when we want.

**Comment by anbraten** [comment]
Those are two issues AFAIK:
- for the max tokens we can use a splitter or one of the other langchain summarzie etc helpers
- for the issues, we should definitely still include them (as they provide quite some helpful context), but we need to improve the fetching to only get updated issues after the first complete fetch when pressing `sync repo`

**Comment by aaa006bd** [comment]
@anbraten All right I will then look up in the langchain for proper size tokenizations. I am opening a PR for this in this issue.
